### ISSUE TITLE
Is there some way to read a file at the top?

### ISSUE THREAD

**Issue by thekofimensah** [python-beaver/python-beaver#445]
I have files that get appended from the top. Is there some way to change it so that I can read every new entry that is at the top of the file?
```
2020/Mar/24;430.804752;0;
2020/Mar/23;430.804752;0;
```
instead of tailing like:
```
2020/Mar/23;430.804752;0;
2020/Mar/24;430.804752;0;
```

**Comment by josegonzalez** [comment]
No, there isn't. Not sure how that would work either, since its not like you can keep a pointer of where you are in the file - you'd have to read the entire file in each time and figure out where you were previously, and by the time you figure that out, the position may have changed so you'd lose data.

I would probably lobby whatever software it is that is creating those datapoints to append the data instead of prepend it.

**Comment by thekofimensah** [comment]
Thanks for the response.  Running this command and reading from the new file

```
tail -r original.csv | diff -u newfile.csv - | grep '^\+'  > newfile.csv
```
